# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options


import pathlib
script_directory = pathlib.Path().absolute()


options = Options()
#options.binary_location = '/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe' 
options.binary_location = '/usr/bin/google-chrome' 

#options.add_argument("user-data-dir=/home/jonas/git/boardgame-vision/selenium")
options.add_argument(f"user-data-dir={script_directory}/selenium-data")

class TestGloomhaven():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()),options = options)
    self.vars = {}
    self.link_list = []

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gloomhaven(self,num_images):
    # Test name: Gloomhaven
    # Step # | name | target | value
    # 1 | open | https://boardgamegeek.com/image/2437871/gloomhaven | 
    #self.driver.manage().window().maximize();
    self.driver.set_window_size(1936, 1056)
    self.driver.get("https://boardgamegeek.com/image/2437871/gloomhaven")
    time.sleep(0.5)
    # 2 | click | css=.tw-right-0 > .svg-inline--fa > path | 
    #self.driver.find_element(By.CSS_SELECTOR, ".tw-right-0 > .svg-inline--fa > path").click()
    # 3 | executeScript | return window.location.href | pageurl
    #self.vars["pageurl"] = self.driver.execute_script("return window.location.href")
    for j in range(num_images):
        #self.driver.find_element(By.CSS_SELECTOR, ".tw-right-0 > .svg-inline--fa > path").click()
        element = self.driver.find_element(By.CSS_SELECTOR,".tw-right-0 > .svg-inline--fa > path")
        webdriver.ActionChains(self.driver).move_to_element(element ).click(element ).perform()
        time.sleep(0.5)
        self.link_list.append(self.driver.execute_script("return window.location.href"))
    print(self.link_list)
    return self.link_list
    

tester=TestGloomhaven()
tester.setup_method(None)
tester.test_gloomhaven(3)
