# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGloomhaven():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gloomhaven(self):
    print("Testing...")
    # Test name: Gloomhaven
    # Step # | name | target | value
    # 1 | open | https://boardgamegeek.com/image/2437871/gloomhaven | 
    self.driver.get("https://boardgamegeek.com/image/2437871/gloomhaven")
    # 2 | click | css=.tw-right-0 > .svg-inline--fa > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".tw-right-0 > .svg-inline--fa > path").click()
    # 3 | executeScript | return window.location.href | pageurl
    self.vars["pageurl"] = self.driver.execute_script("return window.location.href")
    # 4 | echo | ${pageurl} | 
    print("{}".format(self.vars["pageurl"]))
    # 5 | click | css=.tw-right-0 > .svg-inline--fa > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".tw-right-0 > .svg-inline--fa > path").click()
    # 6 | executeScript | return window.location.href | pageurl
    self.vars["pageurl"] = self.driver.execute_script("return window.location.href")
    # 7 | echo | ${pageurl} | 
    print("{}".format(self.vars["pageurl"]))
    # 8 | click | css=.tw-right-0 > .svg-inline--fa > path | 
    self.driver.find_element(By.CSS_SELECTOR, ".tw-right-0 > .svg-inline--fa > path").click()
    # 9 | executeScript | return window.location.href | pageurl
    self.vars["pageurl"] = self.driver.execute_script("return window.location.href")
    # 10 | echo | ${pageurl} | 
    print("{}".format(self.vars["pageurl"]))
  
